### ISSUE TITLE
CSS custom properties (variables) polyfill?

### ISSUE THREAD

**Issue by kaelig** [segmentio/myth#10]
Hi,

I like the idea behind your work, but at the same time it seems very complex to shim some of the principes behind the spec of custom properties.

Custom properties take the cascade into account, for example:
### CSS

``` css
body {
    var-default-font: sans-serif;
}
h1 {
    font-family: var(default-font);
}
#awesome {
    var-default-font: serif;
}
```
### HTML

``` html
<h1>This text: sans-serif</h1>
<div id="awesome">
  <h1>This text: serif</h1>
</div>
```

How does Myth polyfill this use case? If it doesn't, can it be specified in the documentation?
