### ISSUE TITLE
Option to convert units for rem/px fallback from base <html>

### ISSUE THREAD

**Issue by adamcbrewer** [segmentio/myth#52]
I see it's quite common these days to set the font-size on the `html` element to `62.5%` – this is to allow for an easier rem declaration with px fallback. For example:

``` scss
html {
    font-size: 62.5%;
}
body {
    font-size: 16px;
    font-size: 1.6rem;
}
```

However, when I try to use this with Myth I still see the px fallback value as calculated from a `100%` base.

Is there any way to pass in an option to 'adjust' the calculated px value when using rems?
Thanks
