### ISSUE TITLE
Define variables in media-dependent @import

### ISSUE THREAD

**Issue by carlcs** [segmentio/myth#58]
New @import support is working great, but not if I add media queries to it. Variables defined within a imported CSS-file are then being ignored.

Example import.css

``` css
/* Basic import */
@import "import.include-sm.css";

/* Media-dependent import */
@import "import.include-lg.css" (min-width: 64em);
```

import.include-sm.css

``` css
:root {
  --font-size: 2em;
}
.Section {
  font-size: var(--font-size);
}
```

import.include-lg.css

``` css
:root {
  --font-size: 3em;
}
.Section {
  font-size: var(--font-size);
}
```

import.out.css

``` css
/* Basic import */
.Section {
  font-size: 2em;
}

/* Media-dependent import */
@media (min-width: 64em) {
  :root {
    --font-size: 3em;
  }
  .Section {
    font-size: 2em;
  }
}
```
