### ISSUE TITLE
var() doesn’t work when used in media query statement

### ISSUE THREAD

**Issue by paulrobertlloyd** [segmentio/myth#59]
For the following CSS:

``` css
:root {
    --breakpoint_a: 32em;
    --breakpoint_b: 48em;
    --breakpoint_c: 64em;
}

@media screen and (min-width: var(--breakpoint_a)) {
    .container {
        background-color: red;
    }
}
@media screen and (min-width: var(--breakpoint_b)) {
    .container {
        background-color: blue;
    }
}
@media screen and (min-width: var(--breakpoint_c)) {
    .container {
        background-color: green;
    }
}
```

the following CSS is generated:

``` css
@media screen and (min-width: var(--breakpoint_a)) {
    .container {
        background-color: red;
    }
}
@media screen and (min-width: var(--breakpoint_b)) {
    .container {
        background-color: blue;
    }
}
@media screen and (min-width: var(--breakpoint_c)) {
    .container {
        background-color: green;
    }
}
```

Variables work when used as values inside a media query, but not when part of the actual query statement.
