### ISSUE TITLE
Support CSS variables inheritance

### ISSUE THREAD

**Issue by hteumeuleu** [segmentio/myth#63]
Current version 1.0.3 doesn't support CSS variables inheritance. So if we take the following HTML and CSS code :
```html
<div class="block">
	Root Block
</div>
<div class="sidebar">
	<div class="block">
		Sidebar Block
	</div>
</div>
```
```css
:root {
	--large:10px;
}

.sidebar {
	--large:20px;
}

.block {
	padding:var(--large);
}
```
The expected output should be something like this : 
```css
.block {
	padding:10px;
}

.sidebar .block {
	padding:20px;
}
```
This way we respect CSS inheritance, but this may create other issues as it creates more specificity.
