### ISSUE TITLE
Act more like a fallback

### ISSUE THREAD

**Issue by MoOx** [segmentio/myth#64]
Edit: let's go for it
- [x] [rework-vars](https://github.com/reworkcss/rework-vars#preserve-default-false)
- [ ] [rework-custom-media](https://github.com/reworkcss/rework-custom-media/issues/2)
- [ ] rework-hex-alpha
- [ ] rework-rebeccapurple
- [ ] rework-hwb
- [ ] [rework-color-function](https://github.com/ianstormtaylor/rework-color-function/issues/7)
- [ ] rework-font-variant

---

What about adding the possibility to keep original sources & just add rules as fallback before the other ?
If I take you example on the homepage:

``` css
:root {
  --purple: #847AD1;
  --large: 10px;
}

a {
  color: var(--purple);
}
a:hover {
  color: color(var(--purple) tint(20%));
}

pre {
  padding: var(--large);
  margin: calc(var(--large) * 2);
}
```

should yield into

``` css
:root {
  --purple: #847AD1;
  --large: 10px;
}

a {
  color: #847AD1;
  color: var(--purple);
}
a:hover {
  color: rgb(157, 149, 218);
  color: color(var(--purple) tint(20%));
}

pre {
  padding: 10px;
  padding: var(--large);

  margin: 20px;
  margin: calc(var(--large) * 2);
}
```

but instead give (_note that the homepage include `:root` in the output while it's not here_)

``` css
a {
  color: #847AD1;
}

a:hover {
  color: rgb(157, 149, 218);
}

pre {
  padding: 10px;
  margin: 20px;
}
```
