### ISSUE TITLE
@import that @import fails

### ISSUE THREAD

**Issue by MoOx** [segmentio/myth#66]
![we need to go deeper](http://i0.kym-cdn.com/photos/images/original/000/531/557/a88.jpg)

Here is a simple test that fails when you import a file that import a file

`index.css`

``` css
@import "./import.css";
```

`import.css`

``` css
.imported {
  correctly: true;
}

@import "./import2.css";
```

`import2.css`

``` css
.imported2 {
  correctly: true;
}
```

Actual

``` css
.imported {
  correctly: true;
}

@import "./import2.css";
```

Expected ?

``` css
.imported {
  correctly: true;
}

.imported2 {
  correctly: true;
}
```

Is this a desired behavior or is it just I'm pushing myth to far ?
Anyway I'm opening an issue to rework-inline that should go deeper.
