### ISSUE TITLE
First CSS example doesn't work...

### ISSUE THREAD

**Issue by remy** [segmentio/myth#92]
Testing the CSS below (from the README first example) and using myth on the command line gives an exception:

``` text
» myth in.css out.css
       error · Error: property missing ':' near line 8:8
             ·   at error (/usr/local/lib/node_modules/myth/node_modules/rework/node_modules/css/node_modules/css-parse/index.js:57:15)
             ·   at declaration (/usr/local/lib/node_modules/myth/node_modules/rework/node_modules/css/node_modules/css-parse/index.js:189:33)
             ·   at declarations (/usr/local/lib/node_modules/myth/node_modules/rework/node_modules/css/node_modules/css-parse/index.js:219:19)
             ·   at rule (/usr/local/lib/node_modules/myth/node_modules/rework/node_modules/css/node_modules/css-parse/index.js:481:21)
             ·   at rules (/usr/local/lib/node_modules/myth/node_modules/rework/node_modules/css/node_modules/css-parse/index.js:103:56)
             ·   at stylesheet (/usr/local/lib/node_modules/myth/node_modules/rework/node_modules/css/node_modules/css-parse/index.js:73:16)
             ·   at Object.module.exports [as parse] (/usr/local/lib/node_modules/myth/node_modules/rework/node_modules/css/node_modules/css-parse/index.js:485:10)
             ·   at rework (/usr/local/lib/node_modules/myth/node_modules/rework/lib/rework.js:41:25)
             ·   at myth (/usr/local/lib/node_modules/myth/lib/index.js:36:10)
             ·   at /usr/local/lib/node_modules/myth/bin/myth:89:13
```

What's particularly strange about this is that when I use myth in the client side (using the .min.js file), it renders just fine. Any ideas why?

``` css
:root {
  --green: #a6c776;
}

@custom-media --narrow-window screen and (max-width: 30em);

@media (--narrow-window) {
  html {
    font-size: 1.2rem;
  }
}

a {
  color: var(--green);
  font-variant: all-small-caps;
  transition: color 1s;
}

a:hover {
  color: color(var(--green) shade(20%));
}

::placeholder {
  opacity: .4;
  transition: opacity 1s;
}

:focus::placeholder {
  opacity: .2;
}
```
